rabbitmq:
  specificQueueName: specific
  responseQueueName: response
  exchangeName: spring-boot-exchange
  routingKey: foo.bar.#
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_rabbitmq